# NOTE: The data_base_dir must be set by the user
# Either explicitly set it in this file or set it as a command-line argument
# when running the train script.
data_base_dir: "../bubbleml_dataset"
log_dir: "logs/"

train: False  
test: False
benchmark: False
model_checkpoint: 

defaults:
  - _self_
  - dataset: FB_InletVel
  - experiment: experimental/fno/fb_vel
  