# NOTE: The data_base_dir must be set by the user
# Either explicitly set it in this file or set it as a command-line argument
# when running the train script.
data_base_dir:
log_dir:

train: True
test: True

model_checkpoint:

defaults:
  - _self_
  - dataset: 
      name: pb_gravity
      transform: True
      steady_time: 30
      train_paths:
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.0001.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.001.hdf5
          #- ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.01.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.02.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.05.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.1.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.5.hdf5
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-1.0.hdf5
      val_paths:
        - ${data_base_dir}/PoolBoiling-Gravity-FC72-2D/gravY-0.2.hdf5

  - experiment: 
      torch_dataset_name: vel_dataset 
      distributed: True

      train:
        max_epochs: 25
        batch_size: 4
        shuffle_data: True
        time_window: 5
        future_window: 5
        push_forward_steps: 1
        use_coords: False
        noise: True
        downsample_factor: 1

      model:
        model_name: unet_arena
        hidden_channels: 32
        
      optimizer:
        initial_lr: 1e-3
        weight_decay: 0.001 

      lr_scheduler:
        name: cosine
        eta_min: 1e-6
